# Generated by Django 4.2.2 on 2023-06-16 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('singers', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='album_image')),
                ('song', models.FileField(upload_to='uploaded_songs')),
                ('upload_type', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('protected', 'protected')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
