# Generated by Django 4.2.2 on 2023-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsmodel',
            name='upload_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('protected', 'protected')], default='public', max_length=50),
        ),
    ]
