# Generated by Django 4.2.2 on 2023-06-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_songsmodel_upload_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsmodel',
            name='share_to',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
